apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-football
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-football
  template:
    metadata:
      labels:
        app: spring-football
    spec:
      containers:
      - name: spring-football
        image: your-docker-repo/spring-football:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: spring-football
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: spring-football
